### ISSUE TITLE
Can't create new customer

### ISSUE THREAD

**Issue by ahmadalkaid** [diglin/Diglin_Username#26]
Hi,

I add this extension on my project, but I am facing this issue with it on registries form.

`Cannot save the customer.Invalid method Email_Notrequired_Model_Customer_Customer::customerUsernameExists(Array ( [0] => 777774444 [1] => 1 ) )`

You should know that we change the email to be not required, so could you help us please.

**Comment by diglin** [comment]
Hi,

As it is related to the additional module that you installed (Email_Notrequired) and you probably have a conflict between both modules, you must fix the conflict by overwriting one of them in the local code pool. There are plenty tutorials about this topic. Otherwise you will have to hire me.

Best regards
Sylvain

**Comment by diglin** [comment]
no follow -up

**Comment by ahmadalkaid** [comment]
Hi,
Sorry the problem solved, thanks :) .
